import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Wecount Intégration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.card}>
          <div className={styles.theme}>
            <p>User Interface</p>
          </div>
          <h1 className={styles.title}> Service Page Website</h1>
          <div className={styles.description}>Make a page display about services for websites company with blue and red colors</div>
          <div className={styles.friends}>
            <div className={styles.participant}>
              <div className={styles.check}></div>
              <p>0/20</p>
            </div>
            <div className={styles.invitation}>
              <div className={styles.check}></div>
              <div className={styles.check}></div>
              <div className={styles.check}></div>
              <button className={styles.button}>Invite</button>
            </div>
          </div>
          <div className={styles.sharing}>
            4 attachement 
            10 Comment  
          </div>
        </div>
      </main>
    </>
  )
}
